name: flutter_instagram_image_picker
description: Flutter plugin that allows you to display Instagram multi image picker on iOS and Android.
version: 1.1.0+3
homepage: https://github.com/kfiross/flutter_instagram_image_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.6
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
